version: '3.4'

services:
  # Elastic and Kibana
  elastic:
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - elastic

  # PostgreSQL database
  postgres_database:
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  # PostgreSQL pgAdmin Ui
#  pgadmin:
#    ports:
#      - "5050:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    volumes:
#      - pgadmin:/root/.pgadmin
