name: .Net5 CI
on:
  push:
    branches: [ master, develop]
    paths:
      - 'SmartHub/SmartHub.Api/**'
      - 'SmartHub/SmartHub.Api.Tests/**'
      - 'SmartHub/SmartHub.Application.Tests/**'
      - 'SmartHub/SmartHub.Application/**'
      - 'SmartHub/SmartHub.BasePlugin/**'
      - 'SmartHub/SmartHub.Domain.Tests/**'
      - 'SmartHub/SmartHub.Domain/**'
      - 'SmartHub/SmartHub.Infrastructure.Tests/**'
      - 'SmartHub/SmartHub.Infrastructure/**'
      - 'SmartHub/SmartHub.Shared/**'
  pull_request:
    branches: [ master, develop]
    paths:
      - 'SmartHub/SmartHub.Api/**'
      - 'SmartHub/SmartHub.Api.Tests/**'
      - 'SmartHub/SmartHub.Application.Tests/**'
      - 'SmartHub/SmartHub.Application/**'
      - 'SmartHub/SmartHub.BasePlugin/**'
      - 'SmartHub/SmartHub.Domain.Tests/**'
      - 'SmartHub/SmartHub.Domain/**'
      - 'SmartHub/SmartHub.Infrastructure.Tests/**'
      - 'SmartHub/SmartHub.Infrastructure/**'
      - 'SmartHub/SmartHub.Shared/**'

env:
  folderName: 'SmartHub/'
  solution: 'SmartHub.sln'
  
jobs:
  Restore_Build_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Use latest Node.js version
      uses: actions/setup-node@master

    - name: Install dependencies
      run: dotnet restore $folderName$solution
      
    - name: Build with dotnet
      run: dotnet build ${{ format('{0}/{1}', '$folderName', '$solution') }} --configuration Release --no-restore
      
    - name: Run Test
      run: dotnet test ${{ format('{0}/{1}', '$folderName', '$solution') }} --no-restore --verbosity normal
